# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  clienteservicesapi:
    image: clienteservicesapi
    build:
      context: .
      dockerfile: Cliente.Services.Api/Dockerfile
    ports:
      - 2000:2000
